name: de3_loan_dw
version: 1.0.0

profile: de3_loan_dw

model-paths:
  - models

target-path: target
clean-targets:
  - target
  - dbt_packages
  - logs

models:
  de3_loan_dw:
    intermediate:
      +schema: staging
    marts:
      +schema: warehouse
